# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/insuranceaidl',
                'doc_host': 'https://bsalanie.github.io',
                'git_url': 'https://github.com/bsalanie/insuranceaidl',
                'lib_path': 'insuranceaidl'},
  'syms': { 'insuranceaidl.InsuranceAI': {},
            'insuranceaidl.utils': { 'insuranceaidl.utils.read_data': ('utils.html#read_data', 'insuranceaidl/utils.py'),
                                     'insuranceaidl.utils.select_variables': ('utils.html#select_variables', 'insuranceaidl/utils.py')}}}
