# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto 0
__all__ = ['data88', 'y1', 'y2', 'w', 'X']

# %% ../nbs/index.ipynb 4
data88 = read_data("j88")

# %% ../nbs/index.ipynb 6
y1, y2, w, X = select_variables(data88)
